# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Run And Fund' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Run And Fund
  pod 'SVProgressHUD'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SwiftyJSON'
  pod 'Alamofire'

end
